### PR TITLE
Specify theme in exampleSite config

### PR DESCRIPTION
**Pull request by rootkea**
At present:
```
themes/story/exampleSite$ hugo serve -D --themesDir ../..
Total in 53 ms
Error: Error building site: "/home/rootkea/Documents/hacking/hugo/rootkea.gitlab.io/themes/story/exampleSite/content/math.md:19:30": failed to extract shortcode: template for shortcode "math" not found
themes/story/exampleSite$
```

### CODE REVIEW

**Comment by rootkea** [comment]
I guess this is why netlify builds for any PR are failing.

**Comment by rootkea** [comment]
I believe Netlify build command needs to change to:
```
hugo --baseURL https://story.xaprb.com --config exampleSite/config.toml -c exampleSite/content/ --themesDir="../"
```

**Comment by xaprb** [comment]
It's complicated because this theme has to be compatible with the Hugo themes demo site and the way it builds there. Now I no longer remember exactly all the things I needed to change to get it to work correctly, and why. But I put them into the `./start.sh` script so I wouldn't need to remember the correct way to do it. I don't know why your branches' builds are failing on Netlify. The last time I deployed the site to Netlify it worked okay, so I would expect branches to build okay too. I haven't investigated so I don't know anything more helpful to add at this time.

**Comment by xaprb** [comment]
Have you found anything further? Should I close this PR or is there an issue to solve in Story?

**Comment by rootkea** [comment]
> Should I close this PR or is there an issue to solve in Story?

umm.. Depends on whether we would like to let user to test exampleSite (similar to other Hugo themes) or would like user to abort with following error message:
```
themes/story/exampleSite$ hugo serve -D --themesDir ../..
Total in 53 ms
Error: Error building site: "/home/rootkea/Documents/hacking/hugo/rootkea.gitlab.io/themes/story/exampleSite/content/math.md:19:30": failed to extract shortcode: template for shortcode "math" not found
themes/story/exampleSite$
```

**Comment by xaprb** [comment]
I'm confused—I believe my previous comment answered your question. Running the demo site locally works if you use the correct command as I explained. And Netlify succeeds in building the site, when I build from this repo's master branch. You appear to have made some changes in your forked copy, however, that don't succeed. I can't help with that, but perhaps if you diff the repos you'll find what is broken. Therefore if I merge the changes in this PR, I will break the repo and its builds, so I will close the PR.

**Pull request closed without merging**
